language: cpp
compiler: gcc
sudo: required
before_install:
 - chmod +x configure
before_script:
  - sudo add-apt-repository ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-dev libboost-test-dev libboost-thread-dev libboost-system-dev mpi-default-bin mpi-default-dev libboost-all-dev libglm-dev libglew-dev libglewmx-dev libasound2-dev libgl1-mesa-dev libglu1-mesa-dev libpulse-dev libdbus-1-dev libegl1-mesa-dev libgl1-mesa-dev libgles2-mesa-dev libglu1-mesa-dev libts-dev libudev-dev libwayland-dev libx11-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxss-dev libxt-dev libxv-dev libxxf86vm-dev libsdl2-dev libsdl2-image-dev
os:
  -windows
  -linux

#Code to install boost was found here https://devsector.wordpress.com/2014/11/09/github-continuous-integration-with-travis-ci/#boost
