language: cpp
compiler: gcc
sudo: required
before_install:
 - chmod +x configure
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev libboost-test-dev libboost-thread-dev libboost-system-dev
os:
  -windows
  -linux

#Code to install boost was found here https://devsector.wordpress.com/2014/11/09/github-continuous-integration-with-travis-ci/#boost
