language: cpp
compiler: gcc
sudo: required
before_install:
 - chmod +x configure #needed to change permissions to fix build problems.
before_script:
  #Download dependacies not available on apt.
  - wget http://mirrors.kernel.org/ubuntu/pool/main/w/wayland/libwayland-client0_1.4.0-1ubuntu1_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/main/w/wayland/libwayland-server0_1.4.0-1ubuntu1_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/main/w/wayland/libwayland-cursor0_1.4.0-1ubuntu1_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/e/eglibc/libc6_2.19-0ubuntu6.6_amd64.deb
  - wget http://ftp.us.debian.org/debian/pool/main/libs/libsdl2/libsdl2-2.0-0_2.0.2+dfsg1-8_amd64.deb
  - wget http://ftp.us.debian.org/debian/pool/main/libs/libsdl2/libsdl2-dev_2.0.2+dfsg1-8_amd64.deb
  - wget http://ftp.us.debian.org/debian/pool/main/s/sndio/libsndio6.0_1.0.1-2_amd64.deb

  - wget http://mirrors.kernel.org/ubuntu/pool/main/libx/libxkbcommon/libxkbcommon0_0.5.0-1ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-xfixes0_1.8.1-1ubuntu0.2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-dri2-0_1.8.1-1ubuntu0.2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/w/wayland-lts-trusty/libwayland-ltst-server0_1.4.0-1ubuntu1~precise2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/w/wayland-lts-trusty/libwayland-ltst-client0_1.4.0-1ubuntu1~precise2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/l/llvm-toolchain-3.4/libllvm3.4_3.4-1ubuntu3~precise2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/m/mesa-lts-trusty/libgl1-mesa-dri-lts-trusty_10.1.3-0ubuntu0.2~precise2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/m/mesa-lts-trusty/libgbm1-lts-trusty_10.1.3-0ubuntu0.2~precise2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/m/mesa-lts-trusty/libegl1-mesa-lts-trusty_10.1.3-0ubuntu0.2~precise2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/m/mesa-lts-trusty/libwayland-egl1-mesa-lts-trusty_10.1.3-0ubuntu0.2~precise2_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/main/w/wayland/libwayland0_1.4.0-1ubuntu1_all.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/m/mesa/libegl1-mesa-dev_8.0.4-0ubuntu0.6_amd64.deb

  - sudo apt-get update -qq

  #install all dependicies available on apt first.
  - sudo apt-get install -y -q libboost-dev libboost-test-dev libboost-thread-dev libboost-system-dev mpi-default-bin mpi-default-dev libboost-all-dev libglm-dev libglew-dev libasound2-dev libdbus-1-dev libpulse-dev

#libegl1-mesa-dev libgles2-mesa-dev

  #Install manually downloaded dependancies.
  - sudo dpkg -i libc6_2.19-0ubuntu6.6_amd64.deb
  - sudo dpkg -i libsndio6.0_1.0.1-2_amd64.deb


  - sudo dpkg -i libxkbcommon0_0.5.0-1ubuntu2_amd64.deb
  - sudo dpkg -i libxcb-xfixes0_1.8.1-1ubuntu0.2_amd64.deb
  - sudo dpkg -i libxcb-dri2-0_1.8.1-1ubuntu0.2_amd64.deb
  - sudo dpkg -i libwayland-ltst-server0_1.4.0-1ubuntu1~precise2_amd64.deb
  - sudo dpkg -i libwayland-ltst-client0_1.4.0-1ubuntu1~precise2_amd64.deb
  - sudo dpkg -i libllvm3.4_3.4-1ubuntu3~precise2_amd64.deb
  #- sudo dpkg -i libgl1-mesa-dri-lts-trusty_10.1.3-0ubuntu0.2~precise2_amd64.deb
  #- sudo dpkg -i libgbm1-lts-trusty_10.1.3-0ubuntu0.2~precise2_amd64.deb
  #- sudo dpkg -i libegl1-mesa-lts-trusty_10.1.3-0ubuntu0.2~precise2_amd64.deb
  #- sudo dpkg -i libwayland-egl1-mesa-lts-trusty_10.1.3-0ubuntu0.2~precise2_amd64.deb

  #Install problematic conflicting packages.

  - sudo dpkg -i libwayland-client0_1.4.0-1ubuntu1_amd64.deb
  - sudo dpkg -i libwayland-server0_1.4.0-1ubuntu1_amd64.deb
  - sudo dpkg -i libwayland0_1.4.0-1ubuntu1_all.deb
  - sudo dpkg -i libwayland-cursor0_1.4.0-1ubuntu1_amd64.deb
  - sudo dpkg -i libegl1-mesa-dev_8.0.4-0ubuntu0.6_amd64.deb



  - sudo dpkg -i libsdl2-2.0-0_2.0.2+dfsg1-8_amd64.deb
  - sudo dpkg -i libsdl2-dev_2.0.2+dfsg1-8_amd64.deb


os:
  -windows
  -linux

#Code to install boost was found here https://devsector.wordpress.com/2014/11/09/github-continuous-integration-with-travis-ci/#boost
