language: cpp
compiler: gcc
sudo: required
before_install:
 - chmod +x configure #needed to change permissions to fix build problems.
before_script:
  - wget http://ftp.us.debian.org/debian/pool/main/libs/libsdl2/libsdl2-2.0-0_2.0.2+dfsg1-8_amd64.deb
  - wget http://ftp.us.debian.org/debian/pool/main/libs/libsdl2/libsdl2-dev_2.0.2+dfsg1-8_amd64.deb

  - sudo apt-get update -qq

  - sudo apt-get install -y -q libboost-dev libboost-test-dev libboost-thread-dev libboost-system-dev mpi-default-bin mpi-default-dev libboost-all-dev libglm-dev libglew-dev libglewmx-dev libasound2-dev libgbm1 libegl1-mesa libegl1-mesa-drivers libegl1-mesa-dev libgl1-mesa-dev libglu1-mesa-dev libpulse-dev libdbus-1-dev libgles2-mesa-dev libsndio-dev libudev-dev libwayland-dev libxkbcommon-dev libxss-dev libxv-dev libxxf86vm-dev libwayland0 libwayland-egl1-mesa libxkbcommon0

  - sudo dpkg -i libsdl2-2.0-0_2.0.2+dfsg1-8_amd64.deb
  - sudo dpkg -i libsdl2-dev_2.0.2+dfsg1-8_amd64.deb

os:
  -windows
  -linux

#Code to install boost was found here https://devsector.wordpress.com/2014/11/09/github-continuous-integration-with-travis-ci/#boost
